
"use strict";
const K={transactions:"RJKA_v1_transactions",accounts:"RJKA_v1_accounts",budgets:"RJKA_v1_budgets",settings:"RJKA_v1_settings"};
const $=s=>document.querySelector(s), read=(k,d=[])=>{try{return JSON.parse(localStorage.getItem(K[k]))??d}catch{return d}}, save=(k,v)=>localStorage.setItem(K[k],JSON.stringify(v));
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const money=n=>(read("settings",{currency:"₹"}).currency||"₹")+Number(n||0).toLocaleString("en-IN",{minimumFractionDigits:2,maximumFractionDigits:2});
const today=()=>{let d=new Date();return new Date(d-d.getTimezoneOffset()*60000).toISOString().slice(0,10)};
const accounts=()=>read("accounts",[{id:"RJKA-ACC-001",name:"UPI",openingBalance:0},{id:"RJKA-ACC-002",name:"Cash",openingBalance:0},{id:"RJKA-ACC-003",name:"Bank",openingBalance:0}]);
const categories=[["daily_grocery","दररोजचा किराणा खर्च"],["monthly_grocery","महिन्याचा किराणा खर्च"],["travel","प्रवास"],["shopping","खरेदी"],["electricity","लाईट बिल"],["medicine","औषधे"],["mobile","मोबाईल"],["home_emi","घरचा EMI"],["home_maintenance","घरचा मेंटेनन्स"],["other_loan","इतर लोन"],["fish","मच्छी"],["outside_food","बाहेर जेवण"],["insurance_plan","विमा योजना"],["other","Other"]];
const catLabel=id=>categories.find(x=>x[0]===id)?.[1]||id||"—";
const accountLabel=id=>accounts().find(a=>a.id===id)?.name||"खाते हटवले";
const id=prefix=>prefix+"-"+Date.now().toString(36).toUpperCase()+"-"+Math.random().toString(36).slice(2,6).toUpperCase();

const app=$("#app");
function render(){let ac=accounts(),tx=read("transactions"),balances=ac.map(a=>({...a,balance:Number(a.openingBalance||0)+tx.filter(t=>t.accountId===a.id).reduce((s,t)=>s+(t.type==="income"?1:t.type==="expense"?-1:0)*Number(t.amount||0),0)}));
app.innerHTML=`<section class="card"><h2 id="formTitle">नवीन खाते जोडा</h2><form id="form" class="form"><input type="hidden" id="editId"><div class="field"><label>खात्याचे नाव</label><input id="name" maxlength="50" required placeholder="उदा. Savings Account"></div><div class="field"><label>सुरुवातीची शिल्लक (₹)</label><input id="opening" type="number" step="0.01" value="0" required></div><div class="actions"><button class="btn" type="submit">खाते सेव्ह करा</button><button class="btn secondary" type="button" id="cancel" hidden>रद्द करा</button></div></form></section>
<div class="stats"><div class="stat"><small>एकूण खाती</small><strong>${ac.length}</strong></div><div class="stat"><small>एकूण उपलब्ध शिल्लक</small><strong>${money(balances.reduce((s,a)=>s+a.balance,0))}</strong></div></div>
<section class="card"><h2>खात्यांची यादी</h2><div class="table-wrap"><table><thead><tr><th>खाते</th><th>सुरुवातीची शिल्लक</th><th>सध्याची शिल्लक</th><th>व्यवहार</th><th>कृती</th></tr></thead><tbody>${balances.map(a=>`<tr><td><b>${esc(a.name)}</b></td><td>${money(a.openingBalance)}</td><td class="${a.balance<0?"negative":"positive"}">${money(a.balance)}</td><td>${tx.filter(t=>t.accountId===a.id).length}</td><td><button class="btn secondary" data-edit="${esc(a.id)}">Edit</button> <button class="btn danger" data-del="${esc(a.id)}">Delete</button></td></tr>`).join("")||`<tr><td colspan="5" class="empty">खाते उपलब्ध नाही.</td></tr>`}</tbody></table></div><p class="hint">व्यवहार जोडलेले खाते हटवता येणार नाही. खाते हटवण्यापूर्वी त्याचे व्यवहार तपासा.</p></section>`;
$("#form").onsubmit=e=>{e.preventDefault();let all=accounts(),eid=$("#editId").value,name=$("#name").value.trim();if(all.some(a=>a.name.toLowerCase()===name.toLowerCase()&&a.id!==eid)){alert("या नावाचे खाते आधीपासून आहे.");return}if(eid)all=all.map(a=>a.id===eid?{...a,name,openingBalance:Number($("#opening").value)}:a);else all.push({id:id("RJKA-ACC"),name,openingBalance:Number($("#opening").value),createdAt:new Date().toISOString()});save("accounts",all);render()};
$("#cancel").onclick=()=>render();app.querySelectorAll("[data-edit]").forEach(b=>b.onclick=()=>{let a=accounts().find(x=>x.id===b.dataset.edit);if(!a)return;$("#editId").value=a.id;$("#name").value=a.name;$("#opening").value=Number(a.openingBalance||0);$("#formTitle").textContent="खाते संपादित करा";$("#cancel").hidden=false;window.scrollTo({top:0,behavior:"smooth"})});
app.querySelectorAll("[data-del]").forEach(b=>b.onclick=()=>{let aid=b.dataset.del;if(read("transactions").some(t=>t.accountId===aid)){alert("या खात्याशी व्यवहार जोडलेले आहेत. आधी ते व्यवहार दुसऱ्या खात्यात बदला किंवा हटवा.");return}if(confirm("हे खाते हटवायचे आहे का?")){save("accounts",accounts().filter(a=>a.id!==aid));render()}})}render();
