
"use strict";
const K={transactions:"RJKA_v1_transactions",accounts:"RJKA_v1_accounts",budgets:"RJKA_v1_budgets",settings:"RJKA_v1_settings"};
const $=s=>document.querySelector(s), read=(k,d=[])=>{try{return JSON.parse(localStorage.getItem(K[k]))??d}catch{return d}}, save=(k,v)=>localStorage.setItem(K[k],JSON.stringify(v));
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const money=n=>(read("settings",{currency:"₹"}).currency||"₹")+Number(n||0).toLocaleString("en-IN",{minimumFractionDigits:2,maximumFractionDigits:2});
const today=()=>{let d=new Date();return new Date(d-d.getTimezoneOffset()*60000).toISOString().slice(0,10)};
const accounts=()=>read("accounts",[{id:"RJKA-ACC-001",name:"UPI",openingBalance:0},{id:"RJKA-ACC-002",name:"Cash",openingBalance:0},{id:"RJKA-ACC-003",name:"Bank",openingBalance:0}]);
const categories=[["daily_grocery","दररोजचा किराणा खर्च"],["monthly_grocery","महिन्याचा किराणा खर्च"],["travel","प्रवास"],["shopping","खरेदी"],["electricity","लाईट बिल"],["medicine","औषधे"],["mobile","मोबाईल"],["home_emi","घरचा EMI"],["home_maintenance","घरचा मेंटेनन्स"],["other_loan","इतर लोन"],["fish","मच्छी"],["outside_food","बाहेर जेवण"],["insurance_plan","विमा योजना"],["other","Other"]];
const catLabel=id=>categories.find(x=>x[0]===id)?.[1]||id||"—";
const accountLabel=id=>accounts().find(a=>a.id===id)?.name||"खाते हटवले";
const id=prefix=>prefix+"-"+Date.now().toString(36).toUpperCase()+"-"+Math.random().toString(36).slice(2,6).toUpperCase();

const app=$("#app");
function render(){let month=$("#month")?.value||today().slice(0,7),budgets=read("budgets").filter(b=>b.month===month),expenses=read("transactions").filter(t=>t.type==="expense"&&(t.date||"").slice(0,7)===month),totalB=budgets.reduce((s,b)=>s+Number(b.amount||0),0),totalE=expenses.reduce((s,t)=>s+Number(t.amount||0),0);
app.innerHTML=`<section class="card"><h2>बजेट सेट करा</h2><form id="form" class="form"><div class="field"><label>महिना</label><input type="month" id="month" value="${month}" required></div><div class="field"><label>कॅटेगरी</label><select id="category">${categories.map(c=>`<option value="${c[0]}">${c[1]}</option>`).join("")}</select></div><div class="field"><label>बजेट रक्कम (₹)</label><input id="amount" type="number" min="0.01" step="0.01" required placeholder="उदा. 5000"></div><div class="actions"><button class="btn" type="submit">बजेट सेव्ह करा</button></div></form><p class="hint">एकाच महिन्यातील कॅटेगरीसाठी पुन्हा सेव्ह केल्यास विद्यमान बजेट अपडेट होईल.</p></section>
<div class="stats"><div class="stat"><small>एकूण बजेट</small><strong>${money(totalB)}</strong></div><div class="stat"><small>प्रत्यक्ष खर्च</small><strong class="negative">${money(totalE)}</strong></div><div class="stat"><small>उर्वरित बजेट</small><strong class="${totalB-totalE<0?"negative":"positive"}">${money(totalB-totalE)}</strong></div></div>
<section class="card"><h2>बजेट विरुद्ध प्रत्यक्ष खर्च</h2><div class="table-wrap"><table><thead><tr><th>कॅटेगरी</th><th>बजेट</th><th>खर्च</th><th>शिल्लक</th><th>वापर</th><th>कृती</th></tr></thead><tbody>${categories.filter(c=>budgets.some(b=>b.category===c[0])||expenses.some(t=>t.category===c[0])).map(c=>{let b=budgets.find(x=>x.category===c[0]),ba=Number(b?.amount||0),ex=expenses.filter(t=>t.category===c[0]).reduce((s,t)=>s+Number(t.amount||0),0),pct=ba?Math.round(ex/ba*100):0;return `<tr><td>${c[1]}</td><td>${money(ba)}</td><td class="negative">${money(ex)}</td><td class="${ba-ex<0?"negative":"positive"}">${money(ba-ex)}</td><td><div>${ba?pct+"%":"—"}</div><div class="bar ${pct>100?"over":""}"><span style="width:${Math.min(pct,100)}%"></span></div></td><td>${b?`<button class="btn danger" data-del="${esc(b.id)}">Delete</button>`:"—"}</td></tr>`}).join("")||`<tr><td colspan="6" class="empty">या महिन्यासाठी बजेट किंवा खर्च उपलब्ध नाही.</td></tr>`}</tbody></table></div></section>`;
$("#month").onchange=()=>render();$("#form").onsubmit=e=>{e.preventDefault();let all=read("budgets"),m=$("#month").value,c=$("#category").value,a=Number($("#amount").value),old=all.findIndex(b=>b.month===m&&b.category===c);if(old>=0)all[old]={...all[old],amount:a,updatedAt:new Date().toISOString()};else all.push({id:id("BUD"),month:m,category:c,amount:a,createdAt:new Date().toISOString()});save("budgets",all);render()};
app.querySelectorAll("[data-del]").forEach(b=>b.onclick=()=>{if(confirm("हे बजेट हटवायचे आहे का?")){save("budgets",read("budgets").filter(x=>x.id!==b.dataset.del));render()}})}
render();
