"use strict";
(() => {
const K={transactions:"RJKA_v1_transactions",accounts:"RJKA_v1_accounts",settings:"RJKA_v1_settings"};
const cats=[["daily_grocery","दररोजचा किराणा खर्च"],["monthly_grocery","महिन्याचा किराणा खर्च"],["travel","प्रवास"],["shopping","खरेदी"],["electricity","लाईट बिल"],["medicine","औषधे"],["mobile","मोबाईल"],["home_emi","घरचा EMI"],["home_maintenance","घरचा मेंटेनन्स"],["other_loan","इतर लोन"],["fish","मच्छी"],["outside_food","बाहेर जेवण"],["insurance_plan","विमा योजना"],["other","Other"]];
const $=id=>document.getElementById(id), read=(k,d)=>{try{return JSON.parse(localStorage.getItem(k))??d}catch{return d}}, save=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const today=()=>{let d=new Date();d=new Date(d.getTime()-d.getTimezoneOffset()*60000);return d.toISOString().slice(0,10)};
const money=n=>(read(K.settings,{currency:"₹"}).currency||"₹")+Number(n||0).toLocaleString("en-IN",{minimumFractionDigits:2,maximumFractionDigits:2});
let txs=read(K.transactions,[]), accounts=read(K.accounts,[{id:"RJKA-ACC-001",name:"UPI"},{id:"RJKA-ACC-002",name:"Cash"},{id:"RJKA-ACC-003",name:"Bank"}]);
if(!Array.isArray(txs))txs=[];if(!Array.isArray(accounts))accounts=[];
const label=c=>cats.find(x=>x[0]===c)?.[1]||c||"—", acct=id=>accounts.find(a=>a.id===id)?.name||"खाते हटवलेले";
function options(){ $("account").innerHTML=accounts.map(a=>`<option value="${esc(a.id)}">${esc(a.name)}</option>`).join("");$("filterAccount").innerHTML='<option value="all">सर्व खाती</option>'+accounts.map(a=>`<option value="${esc(a.id)}">${esc(a.name)}</option>`).join("");categoryOptions();}
function categoryOptions(){let type=$("type").value;$("category").innerHTML=(type==="income"?[["salary","पगार"],["business","व्यवसाय"],["interest","व्याज"],["gift","भेट"],["refund","परतावा"],["other_income","इतर जमा"]]:cats).map(c=>`<option value="${esc(c[0])}">${esc(c[1])}</option>`).join("")}
function esc(s){return String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function filtered(){let m=$("month").value,t=$("filterType").value,a=$("filterAccount").value,q=$("search").value.trim().toLowerCase();return [...txs].filter(x=>(!m||String(x.date||"").slice(0,7)===m)&&(t==="all"||x.type===t)&&(a==="all"||x.accountId===a)&&(!q||[x.note,label(x.category)].join(" ").toLowerCase().includes(q))).sort((a,b)=>String(b.date||"").localeCompare(String(a.date||""))||String(b.createdAt||"").localeCompare(String(a.createdAt||"")))}
function render(){let arr=filtered(),inc=0,exp=0;arr.forEach(x=>{if(x.type==="income")inc+=+x.amount||0;else exp+=+x.amount||0});$("sumIncome").textContent=money(inc);$("sumExpense").textContent=money(exp);$("sumNet").textContent=money(inc-exp);$("sumNet").className=inc-exp<0?"negative":"positive";$("rows").innerHTML=arr.map(x=>`<tr><td>${esc(x.date||"—")}</td><td class="${x.type==="income"?"positive":"negative"}">${x.type==="income"?"जमा":"खर्च"}</td><td><b>${esc(label(x.category))}</b><small>${esc(x.note||"—")}</small></td><td>${esc(acct(x.accountId))}</td><td class="${x.type==="income"?"positive":"negative"}">${x.type==="income"?"+":"−"}${money(x.amount)}</td><td><button class="btn secondary" data-edit="${esc(x.id)}">Edit</button> <button class="btn danger" data-delete="${esc(x.id)}">हटवा</button></td></tr>`).join("");$("empty").hidden=arr.length>0}
function reset(){ $("txForm").reset();$("editId").value="";$("date").value=today();$("type").value="expense";categoryOptions();$("saveBtn").textContent="व्यवहार सेव्ह करा";$("cancelBtn").hidden=true}
$("type").addEventListener("change",categoryOptions);$("txForm").addEventListener("submit",e=>{e.preventDefault();let id=$("editId").value,old=txs.find(x=>x.id===id);let amount=Number($("amount").value);if(!Number.isFinite(amount)||amount<=0){alert("योग्य रक्कम भरा.");return}let item={id:id||("RJKA-TX-"+Date.now()+"-"+Math.random().toString(36).slice(2,7)),type:$("type").value,date:$("date").value,amount,category:$("category").value,accountId:$("account").value,note:$("note").value.trim(),createdAt:old?.createdAt||new Date().toISOString(),updatedAt:new Date().toISOString()};if(!item.date||!item.accountId){alert("तारीख आणि खाते निवडा.");return}if(id)txs=txs.map(x=>x.id===id?item:x);else txs.push(item);save(K.transactions,txs);reset();render()});
$("rows").addEventListener("click",e=>{let edit=e.target.dataset.edit,del=e.target.dataset.delete;if(edit){let x=txs.find(t=>t.id===edit);if(!x)return;$("editId").value=x.id;$("type").value=x.type;$("date").value=x.date||today();$("amount").value=x.amount;categoryOptions();$("category").value=x.category;$("account").value=x.accountId;$("note").value=x.note||"";$("saveBtn").textContent="बदल सेव्ह करा";$("cancelBtn").hidden=false;window.scrollTo({top:0,behavior:"smooth"})}if(del){let x=txs.find(t=>t.id===del);if(x&&confirm("हा व्यवहार कायमचा हटवायचा आहे का?")){txs=txs.filter(t=>t.id!==del);save(K.transactions,txs);render()}}});
$("cancelBtn").addEventListener("click",reset);["month","filterType","filterAccount","search"].forEach(id=>$(id).addEventListener("input",render));
$("exportBtn").addEventListener("click",()=>{let arr=filtered(),head=["Date","Type","Category","Note","Account","Amount"],lines=[head,...arr.map(x=>[x.date,x.type,label(x.category),x.note,acct(x.accountId),x.amount])].map(row=>row.map(v=>'"'+String(v??"").replace(/"/g,'""')+'"').join(","));let blob=new Blob(["\ufeff"+lines.join("\r\n")],{type:"text/csv;charset=utf-8"}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download="RJKA_transactions.csv";a.click();URL.revokeObjectURL(url)});
options();$("date").value=today();$("month").value=today().slice(0,7);render();
})();
